### ISSUE TITLE
Let it SING

### ISSUE THREAD

**Issue by arpeggio1234** [nlamprian/EMIC2#2]
Hello i like the Emic2 a lot and i use it a lot, just like arduino's and more robotic voices
ginsing, aka babblebot and speakjet, and some more,
Now i tryed for the many times to let the Emic2 sing with the sing command but i can't get this to work.
It sayes Be and then the command codes, i am trying and trying, but nothing seems to work.
I tryed over serial and sending it commands over softwareserial and via a SD-card file.........
no succes. so i use this command 
First p0 to do Dectalk things, and this works okay   s[:rate 200][:n0][:dv ap 90 pr 0] All your base are belong to us.   just sayes  All your base are belong to us     Very nice and good
Then     s[:phone arpa speak on][:rate 200][:n0][dey<650,22>ziy<600,19> dey<650,15>ziy<60gih<200,12>[:n0]
and then it sayes be   and speaks out the the commands. it does not sing
What are the excact commands to send over the serial port the the Rx/Tx port of the Emic2 to let it sing!!!.
Especialy the [:phone arpa speak on]  thing is the problem i think:::::::::  in the songs stands
[:phone arpa speak on] but in the manual stands [:phoneme]   so what will it be, i tryed both and nothing workes. Or do i have to use the sendCmd thing to activate the phoneme stuff???
Wauw and it sounds so nice and clear, please help me out, Dian from the Netherlands

**Comment by deladriere** [comment]
Hi Dian
I think you are missing an ending bracket before the last [:n0]
my strings look like 
("S[:phone arpa speak on][:n0][:rate 60][WIY<500,0>AA<800,0>R_<20>DH AH<100,0> R OW<200,0> B AA<200,0> T S ][:n0]");

**Comment by arpeggio1234** [comment]
What i just found out. I got the pitch values to low, 19 15 12, so it sayed to be but not the rest. I changed the pitch values higher and voila.
Very nice. Happy too. Sometimes coding is........
But the results are realy great.
Thanks Jean-luc for the comment.
Nice to have you around.
Greatings to all. From Dian

**Comment by arpeggio1234** [comment]
Yeah you'r probably right.
I left a ] out and it was right again when it changed the pitches but............
then i had the [] [] [] spelling made right. So now i know it works. 
Thanks again, Dian
